sudo: required
dist: trusty

env:
  global:
    - CXX=g++-4.8
    - PGHOST=localhost
    - PGPORT=5432
    - PGUSER=
    - PGPASSWORD=
    - PGDATABASE=travis_ci_test

before_install:
  - bash scripts/before_install.sh

# Do not insert any code under here without making sures it's in publishingtest first
language: node_js

services:
  - postgresql

addons:
  postgresql: "9.5"
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

node_js:
  - "10"

matrix:
  include:
    - node_js: "10"
      os: osx
    - node_js: "10"
      os: linux

script:
  - createdb travis_ci_test
  - npm run test
  - curl -o package.sh -L https://raw.githubusercontent.com/deepstreamIO/deepstream.io/connector-submodules/scripts/connector/package-connector.sh
  - bash package.sh

deploy:
  - provider: releases
    skip_cleanup: true
    api_key: $GITHUB_TOKEN
    file_glob: true
    file:
      - "build/*.tar.gz"
      - "build/*.zip"
    on:
      tags: true

after_deploy:
  - curl -o test.sh -L https://raw.githubusercontent.com/deepstreamIO/deepstream.io/connector-submodules/scripts/connector/test-connector.sh
  - chmod 555 test.sh
  - ./test.sh

after_script:
  - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
